// Auto-generated by LibreLane
module heichips25_pudding(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input clk,
  input[7:0] ui_in,
  output[7:0] uo_out,
  input[7:0] uio_in,
  output[7:0] uio_out,
  output[7:0] uio_oe,
  input ena,
  input rst_n,
  inout i_in,
  inout i_out
);
endmodule
